#!/bin/bash

\cp ../../default/flux_cal.input .


sed -i "s/flux_cal_dir='..\/..\/..\/..'/flux_cal_dir='..\/..\/..\/..\/..'/g" flux_cal.input
sed -i 's/get_fluxes=.false./get_fluxes=.true./g' flux_cal.input
sed -i "s/dust_topology='h'/dust_topology='c'/g" flux_cal.input
sed -i "s/dust_shape='s'/dust_shape='5'/g" flux_cal.input
