#!/bin/bash

mycheck () {
    if [ $? -ne 0 ]; then
	echo ""
	echo "Installation failed"
	exit 1
    fi
}

curdir=$(pwd)
mycheck

\cd defaults
mycheck
tar -xvzpf tables.tar.gz
mycheck
\cd ..
mycheck

./make
mycheck

echo ""
echo "Checking integrity of installation"
echo ""

\cd test/standard_check
mycheck
./run_test
mycheck
\cd ../../
mycheck

if [ ! -d $HOME/bin ];
   echo "Creating directory $HOME/bin"
   mkdir $HOME/bin
   mycheck
   echo "We recommend you add the line 'export PATH=\"$HOME/bin:$PATH\"' to $HOME/.profile or $HOME/.bashrc."
fi

echo ""
echo "Linking plotting tools to $HOME/bin/."
echo "\ln -s tools/plot_Teff $HOME/bin/."
\ln -s $(pwd)/tools/plot_Teff $HOME/bin/.
mycheck
echo "\ln -s tools/plot_closest $HOME/bin/."
\ln -s $(pwd)/tools/plot_closest $HOME/bin/.
mycheck
echo "\ln -s tools/plot_lc $HOME/bin/."
\ln -s $(pwd)/tools/plot_lc $HOME/bin/.
mycheck

echo ""
echo "Installation completed successfully"


