#!/bin/bash

mycheck () {
    if [ $? -ne 0 ]; then
	echo ""
	echo "Installation failed"
	exit 1
    fi
}

curdir=$(pwd)
mycheck

\cd defaults
mycheck
tar -xvzpf tables.tar.gz
mycheck
\cd ..
mycheck

./make
mycheck

echo ""
echo "Checking integrity of installation"
echo ""

\cd test/standard_check
mycheck
./run_test
mycheck
\cd ../../
mycheck


echo ""
echo "Linking plotting tools to /usr/local/bin/"
echo "\ln -s tools/plot_Teff /usr/local/bin/."
\ln -s tools/plot_Teff /usr/local/bin/.
mycheck
echo "\ln -s tools/plot_closest /usr/local/bin/."
\ln -s tools/plot_closest /usr/local/bin/.
mycheck
echo "\ln -s tools/plot_lc /usr/local/bin/."
\ln -s tools/plot_lc /usr/local/bin/.
echo ""
echo "Installation completed successfully"


