#!/bin/bash

mycheck () {
    if [ $? -ne 0 ]; then
	echo ""
	echo "Integrity check failed"
	exit 1
    fi
}

echo "Checking integrity of files"
echo "This may take up to 10 minutes or so"
echo ""

\cd test/standard_check/test
mycheck
./run
mycheck

echo ""
echo "Integrity check finished"
