#!/bin/bash

mycheck () {
    if [ $? -ne 0 ]; then
	echo ""
	echo "Integrity check failed"
	exit 1
    fi
}

echo "Checking integrity of files"
echo "This may take up to 10 minutes"
echo ""

\cd test/standard_check
mycheck
./run_test
mycheck
\cd ../../
mycheck
