#!/bin/bash

mycheck () {
    if [ $? -ne 0 ]; then
	echo ""
	echo "Uninstallation failed"
	exit 1
    fi
}

echo "Removing linked executable"
echo "\rm -f $HOME/bin/flux_cal"
\rm -f $HOME/bin/flux_cal
mycheck
echo "Removing linked plotting tools"
echo "\rm -f $HOME/bin/plot_Teff"
\rm -f $HOME/bin/plot_Teff
mycheck
echo "\rm -f $HOME/bin/plot_closest"
\rm -f $HOME/bin/plot_closest
mycheck
echo "\rm -f $HOME/bin/plot_lc"
\rm -f $HOME/bin/plot_lc
mycheck
echo ""
echo "Uninstallation completed successfully."
echo "Issue the following commands to remove fluxcal from your system:"
echo "cd .."
echo "rm -rf fluxcal"

