#!/bin/bash

errors=0
originaldirs=( $(find original -name flux_cal | rev | cut -d'/' -f2- | rev) )
testdirs=( $(find test -name flux_cal | rev | cut -d'/' -f2- | rev) )

for i in $(seq 0 $(( ${#originaldirs[@]} - 1 ))); do
    for j in $(find ${originaldirs[i]}/ -type f ! -name 'flux_cal'); do
	diff --brief ${testdirs[i]}/$(basename $j) $j
	if [ $? -ne 0 ]; then
	    errors=$(( $errors + 1 ))
	fi
    done
done

if [[ "$errors" > "0" ]]; then
    echo ""
    echo "*** $errors differences detected. FluxCal is NOT stable. ***"
    echo ""
    diff --brief original/GNUFortran.txt test/GNUFortran.txt
    if [ $? -eq 0 ]; then
	echo "Your version of flux_cal may be corrupted. Please try re-installing."
    else
	echo "Your GNU Fortran version differs. Your version is:"
	head -n1 test/GNUFortran.txt
	echo ""
	echo "The GNU Fortran version used to create 'original' is:"
	head -n1 original/GNUFortran.txt
	echo ""
	echo "Please try installing this version and try again."
    fi
fi
