#!/bin/bash

# This script will run flux_cal in all the directories after cleaning out
# all old output files. Do not run this unless you know what you are doing.
# If you run this on accident, re-download flux_cal from the git page.

check () {
    if [ $? -ne 0 ]; then
	echo "ERROR"
	exit
    fi
}

curdir=$(pwd)
dirlist=( $(find $curdir -name flux_cal | rev | cut -d'/' -f2- | rev) )
check

echo "Removing old files"
rm -f $curdir/GNUFortran.txt
check
for i in ${dirlist[@]}; do
    rmfilelist=( $(find $i -type f ! -name 'fluxcal_0000.dat' -and ! -name 'dimen00000_000_000_000.dat' -and ! -name 'flux_cal' -and ! -name 'flux_cal.input' -and ! -name 'fluxcal.particles') )
    rm -f ${rmfilelist[@]}
    check
done

for i in ${dirlist[@]}; do
    echo "Running $i"
    \cd $curdir/$i
    ./flux_cal > debug
    check
done

\cd $curdir

echo "Writing GNU Fortran version information to GNUFortran.txt"
$(which gfortran) --version > GNUFortran.txt

echo "Done"
