#!/bin/bash

\cp ../default/flux_cal.input .


sed -i 's/get_fluxes=.false./get_fluxes=.true./g' flux_cal.input
sed -i 's/get_integration_at_pos=.false./get_integration_at_pos=.true./g' flux_cal.input

