#!/bin/bash

check () {
    if [ $? -ne 0 ]; then
	echo "ERROR"
	exit
    fi
}

curdir=$(pwd)
dirlist=( $(find . -name flux_cal | rev | cut -d'/' -f2- | rev) )
check

echo "Removing old files"
rm -f GNUFortran.txt
check
for i in ${dirlist[@]}; do
    rmfilelist=( $(find $i -type f ! -name 'fluxcal_0000.dat' -and ! -name 'dimen*.dat' -and ! -name 'flux_cal' -and ! -name 'flux_cal.input' -and ! -name 'fluxcal.particles') )
    rm -f ${rmfilelist[@]}
    check
done
