#!/bin/bash

# This script will run flux_cal in all the directories after cleaning out
# all old output files.

check () {
    if [ $? -ne 0 ]; then
	echo "ERROR"
	exit 1
    fi
}

curdir=$(pwd)
dirlist=( $(find . -name flux_cal | rev | cut -d'/' -f2- | rev) )
check

./clean

for i in ${dirlist[@]}; do
    echo "Running $i"
    \cd $curdir/$i
    ./flux_cal > debug
    check
done

\cd $curdir

echo "Writing GNU Fortran version information to GNUFortran.txt"
$(which gfortran) --version > GNUFortran.txt

echo "Done"
