#!/usr/bin/env python

from __future__ import print_function # Allows python2 and python3 functionality
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable, Divider, Size
from mpl_toolkits.axes_grid1.mpl_axes import Axes
import matplotlib.cm as cm
import matplotlib.colors as cols
import glob
import sys
import matplotlib as mpl
import os.path
import importlib

# This allows the program to be used by both python2 and python3
try:
    input = raw_input
except NameError:
    pass


#runit=6.9598e10
runit=1.e0
tunit=1.e0
tempunit=1.e0
xlim = (None,None)
ylim = (None,None)
Tefflim = (None,None)
logteff = False
cmapname = 'nipy_spectral'
usebb = None
spatialaxesadapt = None
colorbaradapt = None
filepattern = None
paperfriendly = None

fontsize = 12
figsize = (8.0,8.0)
xlabel = "$x$"
ylabel = "$y$"
cbarlabel = "$T_{\\mathrm{eff}}\\ \\left[K\\right]$"
timelabel = "t = {:15.3f}"
rotationslabel = "Rotations (x,y,z) = ({:06.2f}$^o$,{:06.2f}$^o$,{:06.2f}$^o$)"

defaultdir = os.path.dirname(os.path.realpath(__file__))
defaultfile = defaultdir+"/settings_plot_Teff.py"

if os.path.isfile('settings_plot_Teff.py'):
    print("Importing local settings")
    from settings_plot_Teff import *
elif os.path.isfile(defaultfile):
    print("Importing default settings")
    from settings_plot_Teff import *

args = sys.argv[1:]
    
files = []
while len(files) == 0:
    if filepattern is None:
        if args:
            filepattern = args
        else:
            filepattern = input("Enter file name(s) or patterns: ")
    try:
        filepattern = filepattern.split()
    except AttributeError:
        pass
    
    for pattern in filepattern:
        fs = sorted(glob.glob(pattern))
        if len(fs) > 0:
            for i in fs:
                files.append(i)
        else:
            print("ERROR: One or more file pattern not found")
            if args: sys.exit()
            files = []
            filepattern = None
            break
    

if usebb == None:
    loop = True
    while loop:
        user_input = input("Use blackbody color spectrum? (y/n): ")
        if user_input == "y":
            usebb = True
            loop = False
        elif user_input == "n":
            loop = False

if spatialaxesadapt == None:
    loop = True
    while loop:
        user_input = input("Use adaptive limits on spatial axes? (y/n): ")
        if user_input == "y":
            spatialaxesadapt = True
            loop = False
        elif user_input == "n":
            spatialaxesadapt = False
            loop = False
        else:
            print("ERROR: Please respond with 'y' or 'n'.")

if colorbaradapt == None:
    if usebb:
        print("[adaptive limits not available for blackbody spectrum]")
    else:
        loop = True
        while loop:
            user_input = input("Use adaptive limits on colorbar? (y/n): ")
            if user_input == "y":
                colorbaradapt = True
                loop = False
            elif user_input == "n":
                colorbaradapt = False
                loop = False
            else:
                print("ERROR: Please respond with 'y' or 'n'.")

"""
if((spatialaxesadapt == None) and (colorbaradapt == None)):
    loop = True
    while loop:
        user_input = input("Use adaptive plot limits? (y/n): ")
        if user_input == "y":
            #adaptivelimits = True
            loop2 = True
            while loop2:
                user_input = input("On spatial axes? (y/n): ")
                if user_input == "y":
                    spatialaxesadapt = True
                    loop2 = False
                elif user_input == "n":
                    loop2 = False
                else:
                    print("ERROR: Please respond with 'y' or 'n'.")
            loop2 = True
            while loop2 and not usebb:
                user_input = input("On colorbar? (y/n): ")
                if user_input == "y":
                    colorbaradapt = True
                    loop2 = False
                elif user_input == "n":
                    loop2 = False
                else:
                    print("ERROR: Please respond with 'y' or 'n'.")
            loop = False
            if usebb:
                print("[adaptive limits not available for blackbody spectrum]")
        elif user_input == "n":
            spatialaxesadapt = False
            colorbaradapt = False
            loop = False
        else:
            print("ERROR: Please respond with 'y' or 'n'.")
"""
if paperfriendly == None:
    loop = True
    paperfriendly = False
    while loop:
        user_input = input("Paper friendly? [Experimental] (y/n): ")
        if user_input == "y":
            paperfriendly = True
            loop = False
        elif user_input == "n":
            loop = False
        else:
            print("ERROR: Please respond with 'y' or 'n'.")

mpl.rcParams['font.size'] = fontsize
mpl.rcParams['figure.figsize'] = figsize
if paperfriendly:
    # This format is appropriate for ApJ style papers that have
    # two columns of text per page. Each column has a width of
    # 3.5225 inches.
    #mpl.rcParams['font.size'] = 10
    #mpl.rcParams['figure.figsize'] = (3.35225,2.5)
    mpl.rcParams['text.color'] = 'black'
    mpl.rcParams['axes.facecolor'] = '0.95'
    mpl.rcParams['axes.edgecolor'] = 'black'
    mpl.rcParams['axes.labelcolor'] = 'black'
    mpl.rcParams['xtick.color'] = 'black'
    mpl.rcParams['ytick.color'] = 'black'
    mpl.rcParams['figure.facecolor'] = 'white'
    mpl.rcParams['figure.edgecolor'] = 'white'
    mpl.rcParams['figure.subplot.left'] = 0.15
    mpl.rcParams['figure.subplot.right'] = 0.80
    mpl.rcParams['figure.subplot.bottom'] = 0.12
    mpl.rcParams['figure.subplot.top'] = 1.0
    mpl.rcParams['axes.titlepad'] = 0.0
else:
    #mpl.rcParams['font.size'] = 12
    #mpl.rcParams['figure.figsize'] = (8.0,8.0)
    mpl.rcParams['text.color'] = 'white'
    mpl.rcParams['axes.facecolor'] = 'black'
    mpl.rcParams['axes.edgecolor'] = 'white'
    mpl.rcParams['axes.labelcolor'] = 'white'
    mpl.rcParams['xtick.color'] = 'white'
    mpl.rcParams['ytick.color'] = 'white'
    mpl.rcParams['figure.facecolor'] = 'black'
    mpl.rcParams['figure.edgecolor'] = 'black'
    mpl.rcParams['figure.subplot.right'] = 0.85
    mpl.rcParams['figure.subplot.bottom'] = 0.10
    mpl.rcParams['figure.subplot.top'] = 0.95
    mpl.rcParams['figure.titleweight'] = 300


# Setup the matplotlib rcParams
mpl.rcParams['lines.linewidth'] = 1
mpl.rcParams['font.family'] = 'monospace'
mpl.rcParams['font.weight'] = 300
mpl.rcParams['font.monospace'] = 'DejaVu Sans'
mpl.rcParams['mathtext.default'] = 'regular'

mpl.rcParams['xtick.top'] = True
mpl.rcParams['xtick.major.size'] = 9
mpl.rcParams['xtick.minor.size'] = 4
mpl.rcParams['xtick.major.width'] = 0.5
mpl.rcParams['xtick.minor.width'] = 0.5
mpl.rcParams['xtick.labelsize'] = 'medium'
mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['xtick.minor.visible'] = True

mpl.rcParams['ytick.right'] = True
mpl.rcParams['ytick.major.size'] = 9
mpl.rcParams['ytick.minor.size'] = 4
mpl.rcParams['ytick.major.width'] = 0.5
mpl.rcParams['ytick.minor.width'] = 0.5
mpl.rcParams['ytick.labelsize'] = 'medium'
mpl.rcParams['ytick.direction'] = 'in'
mpl.rcParams['ytick.minor.visible'] = True

#mpl.rcParams['font.size'] = 12
#mpl.rcParams['figure.titleweight'] = 300
#mpl.rcParams['figure.figsize'] = (8.0, 8.0)
#mpl.rcParams['figure.subplot.right'] = 0.85
#mpl.rcParams['figure.subplot.bottom'] = 0.10
#mpl.rcParams['figure.subplot.top'] = 0.95

x0win = 0.125
y0win = 0.18273809523809526 - 0.04
x1win = 0.8095238095238095
y1win = 0.8672619047619047 -0.04
        
# Create the plot

fig = plt.figure()
ax = plt.gca()
ax.set_position([x0win,y0win,x1win-x0win,y1win-y0win])
pos = ax.get_position()


# Create the colorbar

if Tefflim[0] != None:
    vmin = Tefflim[0]
if Tefflim[1] != None:
    vmax = Tefflim[1]

mlibcolorbar=False
if usebb:
    Tmin = 0.
    Tmax = 10000.
    try:
        print("Getting live website data for blackbody spectrum colors.")
        import urllib2
        website = 'http://www.vendian.org/mncharity/dir3/blackbody/UnstableURLs/bbr_color.html'
    
        page = urllib2.urlopen(website)
        for i in range(0,20): page.readline() # Skip the header
    
        content = page.readlines()[1:-4][::2]
        content = np.asarray(content)
    
        #content = np.delete(content,0,axis=0)
        bbcols = np.zeros((len(content),4))
        for i in range(0,len(content)):
            content[i] = content[i][34:-17]
            bbcols[i][0] = float(content[i][:5])
            bbcols[i][1] = float(content[i][44:50])
            bbcols[i][2] = float(content[i][51:57])
            bbcols[i][3] = float(content[i][58:64])
    
        Nbbcols = len(bbcols)
        colors = np.reshape(bbcols[:,1:],(Nbbcols,3))
        colors = colors[np.where((bbcols[:,0] > Tmin) & (bbcols[:,0] < Tmax))[0]]
        my_cm = cols.LinearSegmentedColormap.from_list(
            'blackbody', colors, N=Nbbcols)
    except Exception as e:
        print("ERROR:", e)
        print("Getting blackbody spectrum colors from blackbody_temps.dat in the tools directory.")
        success = False
        if not os.path.isfile(defaultdir+"/blackbody_temps.dat"):
            print("ERROR: Could not find file 'blackbody_temps.dat' in the tools directory. Please check your fluxcal installation.")
        else:
            try:
                bbcols = np.genfromtxt(defaultdir+"/blackbody_temps.dat",usecols=(0,6,7,8))
                Nbbcols = len(bbcols)
                colors = np.reshape(bbcols[:,1:],(Nbbcols,3))
                colors = colors[np.where((bbcols[:,0] > Tmin) & (bbcols[:,0] < Tmax))[0]]
                my_cm = cols.LinearSegmentedColormap.from_list(
                    'blackbody', colors, N=Nbbcols)
                success = True
            except Exception as e:
                print("ERROR:",e)
                success = False
        if not success:
            print("Cannot use the blackbody color spectrum. Please fix one of the above errors or choose 'n' at the blackbody color spectrum prompt.")
            sys.exit()
else:
    Tmin = 0.
    Tmax = 0.
    print("Using the colorbar '"+cmapname+"'.")
    try:
        mlibcolorbar = True
        my_cm = plt.cm.get_cmap(cmapname)
    except Exception as e:
        print("FAILED:",e)
        print("ERROR: Please fix the above error and try again.")
        sys.exit()

if usebb and colorbaradapt:
    print("ERROR: It does not make sense to have usebb=True and colorbaradapt=True. The blackbody color spectrum is fixed for given temperatures.")
    sys.exit()
        
if paperfriendly:
    my_cm.set_bad('white',1.)
else:
    my_cm.set_bad('black',1.)
    
#im = plt.imshow([[np.nan],[np.nan]],extent=(ax.get_xlim()[0],ax.get_xlim()[1],ax.get_ylim()[0],ax.get_ylim()[1]),cmap=my_cm)
#pos = ax.get_position()
#cbwidth = 0.03
#cax = fig.add_axes([pos.xmax+0.01,pos.ymin,cbwidth,(pos.ymax-pos.ymin)])
#caxposorig = cax.get_position()
#cb = plt.colorbar(im,cax=cax)
#plt.clim(Tmin,Tmax)
#cb.ax.minorticks_off()

if not spatialaxesadapt or not colorbaradapt:
    # Read all the datafiles and find the maximum viewport
    if not spatialaxesadapt:
        xmaxx = -1e30
        ymaxx = -1e30
        xminn = 1e30
        yminn = 1e30
    if not colorbaradapt:
        aminn = 1.e30
        amaxx = 0.
    for datafile in files:
        grid = np.genfromtxt(datafile,max_rows=1)

        xmin = grid[0]/runit
        hxmap = grid[1]/runit
        nx = int(grid[2])
        ymin = grid[3]/runit
        hymap = grid[4]/runit
        ny = int(grid[5])

        if not spatialaxesadapt:
            xmax = xmin + hxmap * nx
            ymax = ymin + hymap * ny

            xminn = min(xminn,xmin)
            xmaxx = max(xmaxx,xmax)
            yminn = min(yminn,ymin)
            ymaxx = max(ymaxx,ymax)

        if not colorbaradapt:
            if logteff:
                data = np.genfromtxt(datafile,skip_header=1,max_rows=ny)/tempunit
            else:
                data = 10.**(np.genfromtxt(datafile,skip_header=1,max_rows=ny))/tempunit
                data[np.where(data == 0)] = np.nan # Set all T=0 to NaN

            data[np.isinf(data)] = np.nan # Set all inf to NaN
            data[np.isneginf(data)] = np.nan # Set all -inf to NaN

            aminn = min(np.amin(data[np.isfinite(data)]),aminn)
            amaxx = max(np.amax(data[np.isfinite(data)]),amaxx)
        
    if not spatialaxesadapt:
        dx = xmaxx - xminn
        dy = ymaxx - yminn
        if dx > dy:
            ymaxx = yminn + (dy+dx)/2.
            yminn = yminn + (dy-dx)/2.
        elif dx < dy:
            xmaxx = xminn + (dx+dy)/2.
            xminn = xminn + (dx-dy)/2.
        ax.set_aspect(aspect=(xmaxx-xminn)/(ymaxx-yminn))

    if not colorbaradapt and not usebb:
        if Tefflim[0] != None:
            Tmin = Tefflim[0]
        else:
            Tmin = aminn

        if Tefflim[1] != None:
            Tmax = Tefflim[1]
        else:
            Tmax = amaxx

im = plt.imshow([[np.nan],[np.nan]],extent=(ax.get_xlim()[0],ax.get_xlim()[1],ax.get_ylim()[0],ax.get_ylim()[1]),cmap=my_cm)
pos = ax.get_position()
cbwidth = 0.03
cax = fig.add_axes([pos.xmax+0.01,pos.ymin,cbwidth,(pos.ymax-pos.ymin)])
caxposorig = cax.get_position()
cb = plt.colorbar(im,cax=cax)
plt.clim(Tmin,Tmax)
cb.ax.minorticks_off()

cbstate = 0
triggered = [ False, False, False ]
count = 0
for datafile in files:
    # Get the grid data

    hdr = np.genfromtxt(datafile,max_rows=1)
    
    xmin = hdr[0]/runit
    hxmap = hdr[1]/runit
    nx = int(hdr[2])
    ymin = hdr[3]/runit
    hymap = hdr[4]/runit
    ny = int(hdr[5])
    t = hdr[6]/tunit
    
    xmax = xmin + hxmap * nx
    ymax = ymin + hymap * ny

    dx = xmax - xmin
    dy = ymax - ymin

    if not spatialaxesadapt:
        myxmin = xminn
        myxmax = xmaxx
        if xlim[0] != None:
            myxmin = xlim[0]
        if xlim[1] != None:
            myxmax = xlim[1]

        myymin = yminn
        myymax = ymaxx
        if ylim[0] != None:
            myymin = ylim[0]
        if ylim[1] != None:
            myymax = ylim[1]
    
    # Get the Teff data

    if logteff:
        data = np.genfromtxt(datafile,skip_header=1,max_rows=ny)/tempunit
    else:
        data = 10.**(np.genfromtxt(datafile,skip_header=1,max_rows=ny))/tempunit
        data[np.where(data == 0.)] = np.nan # Set all T=0 to NaN

    data[np.isinf(data)] = np.nan # Set all inf to NaN
    data[np.isneginf(data)] = np.nan # Set all -inf to NaN

    amax = np.amax(data[np.isfinite(data)])
    amin = np.amin(data[np.isfinite(data)])

    # Set temperature bounds
    if colorbaradapt:
        #Tmax = amax
        #Tmin = amin
        xlocs = np.zeros(shape=np.shape(data))
        ylocs = np.zeros(shape=np.shape(data))
        for i in range(0,len(xlocs[0])):
            xlocs[:,i] = xmin + hxmap*i
        for i in range(0,len(ylocs)):
            ylocs[i] = ymin + hymap*i

        idx = np.isfinite(data)
        xlocs = xlocs[idx].flatten()
        ylocs = ylocs[idx].flatten()
        flatdata = data[idx].flatten()
        if not spatialaxesadapt:
            idx = np.where(np.logical_and(np.logical_and(xlocs >= myxmin, xlocs <= myxmax),
                                          np.logical_and(ylocs >= myymin, ylocs <= myymax)))[0]
            Tmin = min(flatdata[idx])
            Tmax = max(flatdata[idx])
        else:
            Tmin = amin
            Tmax = amax
        cb.set_clim(Tmin,Tmax)
        cb.update_normal(cax)

    # Plot the data
    im = ax.imshow(data,cmap=my_cm,vmin=Tmin,vmax=Tmax,
                    aspect='equal',extent=(xmin,xmax,ymin,ymax),origin='lower')
            
    if spatialaxesadapt:
        # Center and square the plotted region
    
        if dx > dy:
            ax.set_ylim(ymin + (dy-dx)/2., ymin + (dy+dx)/2.)
        elif dx < dy:
            ax.set_xlim(xmin + (dx-dy)/2., xmin + (dx+dy)/2.)
    else:
        ax.set_xlim(myxmin,myxmax)
        ax.set_ylim(myymin,myymax)
        ax.set_aspect(aspect=(myxmax-myxmin)/(myymax-myymin))

    
    # Resize colorbar and put arrow on it for stuff out of bounds
    if not colorbaradapt:
        cbstateold = cbstate
        # cbstate = 0 no arrows
        # cbstate = 1 top arrow
        # cbstate = 2 bottom arrow
        # cbstate = 3 both arrows
        cbstate = 0 # No arrows
        if amax > Tmax: # top arrow
            triggered[0] = True
            cbstate = 1
        if amin < Tmin: # bottom arrow
            triggered[1] = True
            cbstate = 2
        if((amax > Tmax) and (amin < Tmin)): # both arrows
            triggered[2] = True
            cbstate = 3
        height = caxposorig.height
        x0 = caxposorig.x0 + 0.0007
        y0 = caxposorig.y0
        width = caxposorig.width
        if triggered[0]:
            height = height + 0.034
        if triggered[1]:
            y0 = y0 - 0.034
            height = height + 0.034

        if cbstate == 0:
            cb.extend = 'neither'
        elif cbstate == 1:
            cb.extend = 'max'
        elif cbstate == 2:
            cb.extend = 'min'
        elif cbstate == 3:
            cb.extend = 'both'

        if (cbstateold != cbstate) or (count==0):
            cax.set_position([x0,y0,width,height])
            cb._inside = cb._slice_dict[cb.extend]
            cb.update_normal(cax)


    # Re-plot the axis labels

    ax.annotate(xlabel,((pos.x0+pos.x1)/2.,0.05),xycoords='figure fraction', ha='center')
    ax.annotate(ylabel,(0.0,(pos.y1+pos.y0)/2.),xycoords='figure fraction', ha='left',va='center',rotation='vertical')
    ax.annotate(cbarlabel,(1.0,(pos.y1+pos.y0)/2.),xycoords='figure fraction', va='center',ha='right',rotation='vertical')

    
    # Update the plot title
    
    rotations = datafile.split("/")[-1][12:-4].split("_")
    xdeg = int(rotations[0])
    ydeg = int(rotations[1])
    zdeg = int(rotations[2])
    if not paperfriendly:
        ax.annotate(timelabel.format(t),(pos.x0,(1.+pos.y1)/2.+0.015),xycoords='figure fraction',ha='left')
        ax.annotate(rotationslabel.format(xdeg,ydeg,zdeg),(pos.x0,(1.+pos.y1)/2.-0.015),xycoords='figure fraction', ha='left')


    # Save the image

    savename = "teffs"+datafile.split("/")[-1][5:-4]
    if paperfriendly:
        savename = savename+".eps"
    else:
        savename = savename+".png"
    print("Saving", savename)
    plt.savefig(savename,facecolor=fig.get_facecolor())

    # Clear the axis
    ax.clear()
    count+=1

print("Finished.")
if len(files) > 1:
    print("")
    print("Try some of these commands to make a movie:")
    print(".avi: mencoder mf://teffs*.png -mf w=800:h=800:fps=25:type=png -ovc copy -oac copy -o teffs.avi")
    print(".mpg: mencoder mf://teffs*.png -mf w=800:h=800:fps=25:type=png -of mpeg -ovc lavc -lavcopts vcodec=mpeg1video -o teffs.mpg")
    print(".gif: convert -delay 10 -loop 0 teffs*.png teffs.gif")

