#!/bin/bash

\cp ../default/flux_cal.input .


sed -i 's/track_particles=.false./track_particles=.true./g' flux_cal.input
sed -i 's/binary_tracking_file=.false./binary_tracking_file=.true./g' flux_cal.input
